#!/usr/bin/sh
# Iniciar configuracion de pantalla

if [[ $(xrandr -q | grep 'HDMI-A-0 connected') ]]; then 
# Configuracion con doble pantalla
xrandr --output eDP --primary --mode 1920x1080 --rotate normal --output HDMI-A-0 --mode 1920x1080 --rotate normal --left-of eDP
#xrandr --output eDP --primary --mode 1920x1080 --rotate normal --output HDMI-A-0 --mode 1280x1024 --refresh 75.02 --rotate normal --left-of eDP

bspc monitor eDP      -d 0 1 2 3 4
bspc monitor HDMI-A-0 -d 5 6 7 8 9
# Iniciar polybar en dos monitores
~/.config/polybar/launch.sh --hdmi &
# Configuracion para un solo monitor
else
xrandr --output eDP --primary --mode 1920x1080 --rotate normal

bspc monitor eDP      -d 0 1 2 3 4 5 
# Iniciar polybar despues de configurar la pantalla 
~/.config/polybar/launch.sh --pwidgets &
fi

# Arrancar shortcuts
sxhkd &

bspc config border_width         1
bspc config window_gap           8

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Pantalla y transparencias
nitrogen --restore &
#picom --config /home/kobayashi/.config/picom/picom.conf &
picom &

# Desactivar campana
xset b off
